#                                              BILLING SYSTEM PROJECT

: We have assigned to build a software for one of our client. Which should fullfill the following requirements

## objective :-
    
    To make a software which can uploaded to a device to interact, update, modify the existing backend database and generate 
    the the bills of transactions

In [12]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\shubham\appdata\roaming\python\python39\site-packages (8.0.31)
Requirement already satisfied: protobuf<=3.20.1,>=3.11.0 in c:\programdata\anaconda3\lib\site-packages (from mysql-connector-python) (3.19.1)

In [13]:
!pip install mysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql in c:\users\shubham\appdata\roaming\python\python39\site-packages (0.0.3)
Requirement already satisfied: mysqlclient in c:\users\shubham\appdata\roaming\python\python39\site-packages (from mysql) (2.1.1)

In [21]:
# importing important libraries

import mysql.connector as connector
from datetime import datetime

In [2]:
# setting global veriables
global conn, cursor

In [3]:
# connecting TO Database in SQL Server
conn= connector.connect(host="localhost",database="billing_software",
      user="root",password="Shubham@007",auth_plugin='mysql_native_password')
cursor = conn.cursor()

In [4]:
# Creating Some Useful Functions

def clear():
    for _ in range(5):
        print()

In [18]:
# To get the Last bill no

def last_bill_no():
    cursor.execute('select max(bill_id) from bills')
    record = cursor.fetchone()
    return record

In [5]:
# this function is for finding existing details
def find_item(no):
    cursor.execute(f'select * from items where id ={no}')
    record = cursor.fetchone()
    return record

In [6]:
# - as refrence to understand above command
n = int(input("Enter the item no: "))

cursor.execute(f'select * from items where id = {n}')

cursor.fetchall()

Enter the item no: 204

[(204, 'Tea Cattel', 240.0)]

In [59]:
# To add the new item, if not present/display in the items table
def add_item():
    clear()
    print('Add New Item - Screen')
    print('-'*100)
    item_name = input('Enter new Item Name : ')
    sql = f'select * from items where item_name like "%{item_name.title()}%"'
    cursor.execute(sql)
    record=cursor.fetchone()
    if record==None:
        price = float(input('Enter Item Price : '))
        n_id = int(input("Enter The Item Id: "))
        sql = f'insert into items(id,item_name,price) values({n_id},"{item_name.title()}",{price});'
        cursor.execute(sql)
        print('\n\nNew Item added successfully.....\nPress any key to continue....')
    else:
        print('\n\nItem Name already Exist.....\nPress any key to continue....')
    wait= input()

In [58]:
print('Add New Item - Screen')
print('-'*100)
item_name = input('Enter new Item Name : ')
sql = f'select * from items where item_name like "%{item_name.title()}%"'
cursor.execute(sql)
record=cursor.fetchone()
if record==None:
    price = float(input('Enter Item Price : '))
    n_id = int(input("Enter The Item Id: "))
    sql = f'insert into items(id,item_name,price) values({n_id},"{item_name.title()}",{price});'
    cursor.execute(sql)
    print('\n\nNew Item added successfully.....\nPress any key to continue....')
else:
    print('\n\nItem Name already Exist.....\nPress any key to continue....')
wait= input()

Add New Item - Screen
----------------------------------------------------------------------------------------------------
Enter new Item Name : Footboll
Enter Item Price : 3000
Enter The Item Id: 509


New Item added successfully.....
Press any key to continue....

In [10]:
def item_list():
    clear()
    sql="select * from items"
    cursor.execute(sql)
    records = cursor.fetchall()
    for row in records:
        print(row)
    print('\nPress any key to continue.....')
    wait = input()

In [9]:
sql="select * from items"
cursor.execute(sql)
records = cursor.fetchall()
for row in records:
    print(row)
print('\nPress any key to continue.....')
wait = input()

(201, 'Fash wash', 250.75)
(202, 'Perfume', 2500.0)
(203, 'Deodrent', 199.0)
(204, 'Tea Cattel', 240.0)
(205, 'Condoms', 143.0)
(206, 'Hair dryer', 175.0)
(207, 'Suns Cream', 275.0)
(208, 'hair oil', 250.75)
(209, 'Trimmer', 999.0)
(210, 'Eye liner', 1299.0)
(301, 'Feuits & vegetables', 100.0)
(302, 'Meat & Seafood', 1999.0)
(303, 'Coffe', 299.0)
(304, 'Tea powder', 199.0)
(305, 'soups', 99.0)
(306, 'Sauce', 149.0)
(307, 'Cadbary', 179.0)
(308, 'Pasta', 299.0)
(309, 'bread', 299.0)
(310, 'oats', 299.0)
(401, 'Swimsuite', 499.0)
(402, 'Jeans', 999.0)
(403, 'Shirts', 799.0)
(404, 'Skirts', 899.0)
(405, 'Bra', 399.0)
(406, 'Tops', 499.0)
(407, 'gown', 1499.0)
(408, 'Slip', 599.0)
(409, 'babydoll', 499.0)
(410, 'Shorts', 341.0)
(506, 'Milk Product', 75.0)

Press any key to continue.....

In [2]:
# To modify list of items
def modify_item():
    clear()
    print('Modify Item Details - Screen')
    print('-'*100)
    item_id = input('Enter Item ID :')
    item_name = input('Enter New Item Name :')
    item_price = float(input('Enter Item Price :'))
    sql = f'update items set item_name = "{item_name}", price ={item_price} where id={item_id}'    
    cursor.execute(sql)
    print('\n\nRecord Updated Successfully............')

In [11]:
print('Modify Item Details - Screen')
print('-'*100)
item_id = input('Enter Item ID :')
item_name = input('Enter New Item Name :')
item_price = float(input('Enter Item Price :'))
sql = f'update items set item_name = "{item_name}", price ={item_price} where id={item_id}'
cursor.execute(sql)
print('\n\nRecord Updated Successfully............')

Modify Item Details - Screen
----------------------------------------------------------------------------------------------------
Enter Item ID :503
Enter New Item Name :butter
Enter Item Price :140


Record Updated Successfully............

In [12]:
item_list()

(201, 'Fash wash', 250.75)
(202, 'Perfume', 2500.0)
(203, 'Deodrent', 199.0)
(204, 'Tea Cattel', 240.0)
(205, 'Condoms', 143.0)
(206, 'Hair dryer', 175.0)
(207, 'Suns Cream', 275.0)
(208, 'hair oil', 250.75)
(209, 'Trimmer', 999.0)
(210, 'Eye liner', 1299.0)
(301, 'Feuits & vegetables', 100.0)
(302, 'Meat & Seafood', 1999.0)
(303, 'Coffe', 299.0)
(304, 'Tea powder', 199.0)
(305, 'soups', 99.0)
(306, 'Sauce', 149.0)
(307, 'Cadbary', 179.0)
(308, 'Pasta', 299.0)
(309, 'bread', 299.0)
(310, 'oats', 299.0)
(401, 'Swimsuite', 499.0)
(402, 'Jeans', 999.0)
(403, 'Shirts', 799.0)
(404, 'Skirts', 899.0)
(405, 'Bra', 399.0)
(406, 'Tops', 499.0)
(407, 'gown', 1499.0)
(408, 'Slip', 599.0)
(409, 'babydoll', 499.0)
(410, 'Shorts', 341.0)
(506, 'Milk Product', 75.0)

Press any key to continue.....

In [23]:
# To showcase bill strcture 
def billing():
    items =[]

    bill_no = last_bill_no()
    if bill_no[0]==None:
        bill_no =1
    else:
        bill_no = bill_no[0]+1 

    name = input('Enter customer Name :')
    print("Name of Customer: ",name)

    phone = input('Enter Phone No :')
    print("Phone No of Customer: ", phone)

    dt = input("Enter the Date Purchase (format='YYYY-MM-DD') : ")
    print("The Date of Purchase is: ",dt)
    dtt = datetime.strptime(dt,'%Y-%m-%d')
    dtt = dtt.date()


    while True:
        no = int(input('Enter item No (0 to stop) :'))
        if no <=0:
            break
        else:
            item = find_item(no)
            if item==None:
                print('Item Not found  ')
            else:
                qty = int(input('Enter Item Qty :'))
                item = list(item)
                item.append(qty)
                items.append(item)
    print(item)
    print(items)



    clear()
    print('                     Absolute Solution              ')
    print('                     D- Block Chander Nagar, GZB     ')
    print('                     Phone: 9871816901, Email: rakesh@binarynote.com ')
    print(f'Bill No :{bill_no}        Date :{dt}')
    print('-'*100)
    print(f'Customer Name :{name}          Phone No :{phone}')
    print('-'*100)
    print('Item Id     Item Name                Price            Qty         Amount ')
    print('-'*100)

    total =0

    for item in items:
        print('Item Id\t\t Item Name\t\t Price\t\t Qty\t\t Amount ')

        print(f"{item[0]}\t\t {item[1]}\t\t {item[2]}\t\t {item[3]}\t\t {round(item[2]*item[3],2)} ")

        total = total +item[2]*item[3]


    print('-'*100)

    print(f'Total Payable Amount : {round(total,2)}')

    print('\nPress any key to continue........')


    # Getting the letest transaction id
    cursor.execute("select max(id) from transactions")
    prev_tid = cursor.fetchone()[0]


    # Getting the letest bill id
    cursor.execute("select max(bill_id) from bills")
    prev_bid = cursor.fetchone()[0]





    #insert data into tables

    sql = f'insert into bills values({prev_bid+1}, "{name}", "{phone}", "{dtt}");'
    cursor.execute(sql)    
    for item in items:

        sql= f'insert into transactions values({prev_tid+1}, {item[0]}, {item[3]}, {bill_no});'
        cursor.execute(sql)
        prev_tid += prev_tid + 1

    wait= input()

In [22]:
items =[]

bill_no = last_bill_no()
if bill_no[0]==None:
    bill_no =1
else:
    bill_no = bill_no[0]+1 
    
name = input('Enter customer Name :')
print("Name of Customer: ",name)

phone = input('Enter Phone No :')
print("Phone No of Customer: ", phone)

dt = input("Enter the Date Purchase (format='YYYY-MM-DD') : ")
print("The Date of Purchase is: ",dt)
dtt = datetime.strptime(dt,'%Y-%m-%d')
dtt = dtt.date()


while True:
    no = int(input('Enter item No (0 to stop) :'))
    if no <=0:
        break
    else:
        item = find_item(no)
        if item==None:
            print('Item Not found  ')
        else:
            qty = int(input('Enter Item Qty :'))
            item = list(item)
            item.append(qty)
            items.append(item)
print(item)
print(items)



clear()
print('                     Absolute Solution              ')
print('                     D- Block Chander Nagar, GZB     ')
print('                     Phone: 9871816901, Email: rakesh@binarynote.com ')
print(f'Bill No :{bill_no}        Date :{dt}')
print('-'*100)
print(f'Customer Name :{name}          Phone No :{phone}')
print('-'*100)
print('Item Id     Item Name                Price            Qty         Amount ')
print('-'*100)

total =0

for item in items:
    print('Item Id\t\t Item Name\t\t Price\t\t Qty\t\t Amount ')
    
    print(f"{item[0]}\t\t {item[1]}\t\t {item[2]}\t\t {item[3]}\t\t {round(item[2]*item[3],2)} ")
    
    total = total +item[2]*item[3]
    
    
print('-'*100)

print(f'Total Payable Amount : {round(total,2)}')

print('\nPress any key to continue........')


# Getting the letest transaction id
cursor.execute("select max(id) from transactions")
prev_tid = cursor.fetchone()[0]


# Getting the letest bill id
cursor.execute("select max(bill_id) from bills")
prev_bid = cursor.fetchone()[0]





#insert data into tables

sql = f'insert into bills values({prev_bid+1}, "{name}", "{phone}", "{dtt}");'
cursor.execute(sql)    
for item in items:

    sql= f'insert into transactions values({prev_tid+1}, {item[0]}, {item[3]}, {bill_no});'
    cursor.execute(sql)
    prev_tid += prev_tid + 1
    
wait= input()

Enter customer Name :Jabya
Name of Customer:  Jabya
Enter Phone No :4855
Phone No of Customer:  4855
Enter the Date Purchase (format='YYYY-MM-DD') : 2022-03-21
The Date of Purchase is:  2022-03-21
Enter item No (0 to stop) :404
Enter Item Qty :50
Enter item No (0 to stop) :506
Enter Item Qty :10
Enter item No (0 to stop) :-1
[506, 'Milk Product', 75.0, 10]
[[404, 'Skirts', 899.0, 50], [506, 'Milk Product', 75.0, 10]]





                     Absolute Solution
                     D- Block Chander Nagar, GZB
                     Phone: 9871816901, Email: rakesh@binarynote.com
Bill No :26        Date :2022-03-21
----------------------------------------------------------------------------------------------------
Customer Name :Jabya          Phone No :4855
----------------------------------------------------------------------------------------------------
Item Id     Item Name                Price            Qty         Amount
----------------------------------------------------------------------------------------------------
Item Id		 Item Name		 Price		 Qty		 Amount
404		 Skirts		 899.0		 50		 44950.0
Item Id		 Item Name		 Price		 Qty		 Amount
506		 Milk Product		 75.0		 10		 750.0
----------------------------------------------------------------------------------------------------
Total Payable Amount : 45700.0

Press any key to continue........

In [3]:
# To get sale by datetime
def date_wise_sell():
    clear()

    print('Sell Between Two Dates -- Screen')
    print('-'*100)
    start_date = input('Enter start Date (YYYY-MM-DD) :')
    end_date   = input('Enter End Date (YYYY-MM-DD) :')

    sql = f'select * from bills where bill_date between "{start_date}" and "{end_date}"'

    cursor.execute(sql)
    records = cursor.fetchall()

    clear()

    print('Bill No\t Customer Name\t\t Phone No    \t Bill Date')

    print('-'*100)

    for row in records:
        print(f'{row[0]:<10d} {row[1]:20s} {row[2]:20s} {row[3]}')

    print('-'*100)

    print('\n\nPress any key to continue....')

    wait= input()

In [25]:
print('Sell Between Two Dates -- Screen')
print('-'*100)
start_date = input('Enter start Date (YYYY-MM-DD) :')
end_date   = input('Enter End Date (YYYY-MM-DD) :')

sql = f'select * from bills where bill_date between "{start_date}" and "{end_date}"'

cursor.execute(sql)
records = cursor.fetchall()

clear()

print('Bill No\t Customer Name\t\t Phone No    \t Bill Date')

print('-'*100)

for row in records:
    print(f'{row[0]:<10d} {row[1]:20s} {row[2]:20s} {row[3]}')
    
print('-'*100)

print('\n\nPress any key to continue....')

wait= input()

Sell Between Two Dates -- Screen
----------------------------------------------------------------------------------------------------
Enter start Date (YYYY-MM-DD) :2022-03-01
Enter End Date (YYYY-MM-DD) :2022-03-10





Bill No	 Customer Name		 Phone No    	 Bill Date
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------


Press any key to continue....

In [30]:
def bill_information():
    clear()
    bill_no = input('Enter Bill Number :')

    sql = F"""select b.bill_id, b.name, b.phone, b.bill_date, t.item_id,t.qty,i.item_name,
       i.price from bills b,transactions t,items i 
       where b.bill_id = t.bill_id AND t.item_id= i.id AND 
       b.bill_id ={bill_no};"""


    cursor.execute(sql) 

    records = cursor.fetchall()

    n = cursor.rowcount

    clear()

    print("Bill No :",bill_no)
    print('-'*100)

    if n<=0:
        print(f'Bill number {bill_no} does not exists')

    else:
        print(f'Customer Name : {records[0][1]}  Phone No :{records[0][2]}')

        print(f'Bill Date : {records[0][3]}'.format(records[0][3]))

        print('-'*100)

        print('{:10s} {:30s} {:20s} {:10s} {:30s}'.format('ID','Item Name','Qty',
             'Price','Amount'))
        print('-'*100)

        for row in records:
            print('{:<10d} {:30s} {:<20d} {:.2f}    {:>.2f}'.format(row[4],row[6],row[5],row[7],row[5]*row[7]))

        print('-'*100)

    print('\nPress any key to continue....')
    wait = input()

In [29]:
bill_no = input('Enter Bill Number :')

sql = F"""select b.bill_id, b.name, b.phone, b.bill_date, t.item_id,t.qty,i.item_name,
       i.price from bills b,transactions t,items i 
       where b.bill_id = t.bill_id AND t.item_id= i.id AND 
       b.bill_id ={bill_no};"""

cursor.execute(sql) 

records = cursor.fetchall()

n = cursor.rowcount

clear()

print("Bill No :",bill_no)
print('-'*100)

if n<=0:
    print(f'Bill number {bill_no} does not exists')

else:
    print(f'Customer Name : {records[0][1]}  Phone No :{records[0][2]}')
    
    print(f'Bill Date : {records[0][3]}'.format(records[0][3]))
    
    print('-'*100)
    
    print('{:10s} {:30s} {:20s} {:10s} {:30s}'.format('ID','Item Name','Qty',
         'Price','Amount'))
    print('-'*100)
    
    for row in records:
        print('{:<10d} {:30s} {:<20d} {:.2f}    {:>.2f}'.format(row[4],row[6],row[5],row[7],row[5]*row[7]))
    
    print('-'*100)

print('\nPress any key to continue....')
wait = input()

Enter Bill Number :1





Bill No : 1
----------------------------------------------------------------------------------------------------
Customer Name : Guddi  Phone No :9762207797
Bill Date : 2020-01-23
----------------------------------------------------------------------------------------------------
ID         Item Name                      Qty                  Price      Amount
----------------------------------------------------------------------------------------------------
208        hair oil                       1                    250.75    250.75
----------------------------------------------------------------------------------------------------

Press any key to continue....

In [4]:
# To get overall collection as per date 
def amount_collected():
    clear()
    
    start_date = input('Enter start Date (YYYY-MM-DD) :')
    end_date   = input('Enter End   Date (YYYY-MM-DD) :')
    clear()

    print(f'Amount collected between: {start_date} and {end_date}')
    print('-'*100)

    sql = f'select round(sum(t.qty*i.price),2) from bills b,transactions t,items i \
           where b.bill_date between "{start_date}" AND "{end_date}" AND b.bill_id = t.bill_id AND \
           t.item_id = i.id;'
    cursor.execute(sql)
    result = cursor.fetchone()[0]

    print(result)

    print('\nPress any key to continue.....')
    wait= input()

In [37]:
start_date = input('Enter start Date (YYYY-MM-DD) :')
end_date   = input('Enter End   Date (YYYY-MM-DD) :')
clear()

print(f'Amount collected between: {start_date} and {end_date}')
print('-'*100)

sql = f'select round(sum(t.qty*i.price),2) from bills b,transactions t,items i \
       where b.bill_date between "{start_date}" AND "{end_date}" AND b.bill_id = t.bill_id AND \
       t.item_id = i.id;'
cursor.execute(sql)
result = cursor.fetchone()[0]

print(result)

print('\nPress any key to continue.....')
wait= input()

Enter start Date (YYYY-MM-DD) :2020-01-03
Enter End   Date (YYYY-MM-DD) :2020-01-15





Amount collected between: 2020-01-03 and 2020-01-15
----------------------------------------------------------------------------------------------------
91026.75

Press any key to continue.....

In [41]:
def search_item():
    clear()
    item_name =input('Enter Item Name :')
    sql ='select * from items where item_name like "%{}%";'.format(item_name)
    cursor.execute(sql)
    records = cursor.fetchall()
    clear()
    print('Item Names start with :',item_name)
    print('-'*100)
    print('{:10s} {:30s} {:20s}'.format('Item ID','Item Name','Item Price'))
    print('-'*100)
    for row in records:
        print('{:<10d} {:30s} {:.2f}'.format(row[0],row[1],row[2]))
    print('-'*100)
    print('\nPress any key to continue....')
    wait= input()

In [38]:
item_name =input('Enter Item Name :')

sql ='select * from items where item_name like "%{}%";'.format(item_name)
cursor.execute(sql)
records = cursor.fetchall()

clear()

print('Item Names start with :',item_name)
print('-'*100)
print('{:10s} {:30s} {:20s}'.format('Item ID','Item Name','Item Price'))
print('-'*100)

for row in records:
    print(f'{row[0]:<10d} {row[1]:30s} {row[2]:.2f}')
print('-'*100)
print('\nPress any key to continue....')
wait= input()

Enter Item Name :babydoll





Item Names start with : babydoll
----------------------------------------------------------------------------------------------------
Item ID    Item Name                      Item Price
----------------------------------------------------------------------------------------------------
409        babydoll                       499.00
----------------------------------------------------------------------------------------------------

Press any key to continue....

In [42]:
def search_customer():
    clear()
    cust_name =input('Enter customer Name :')
    sql =f'select * from bills where name like "%{cust_name}%";'
    cursor.execute(sql)
    records = cursor.fetchall()
    clear()

    print('Customer Names started with :',cust_name)
    print('-'*100)
    print('{:10s} {:30s} {:20s} {:20s}'.format('Bill No','Customer Name',
            'Phone No','Bill Date'))

    print('-'*100)
    for row in records:
        print(f'{row[0]:<10d} {row[1]:30s} {row[2]:20s} {str(row[3]):20s}')
    print('-'*100)
    print('\nPress any key to continue....')
    wait= input()

In [39]:
cust_name =input('Enter customer Name :')
sql =f'select * from bills where name like "%{cust_name}%";'
cursor.execute(sql)
records = cursor.fetchall()
clear()

print('Customer Names started with :',cust_name)
print('-'*100)
print('{:10s} {:30s} {:20s} {:20s}'.format('Bill No','Customer Name',
        'Phone No','Bill Date'))

print('-'*100)
for row in records:
    print(f'{row[0]:<10d} {row[1]:30s} {row[2]:20s} {str(row[3]):20s}')
print('-'*100)
print('\nPress any key to continue....')
wait= input()

Enter customer Name :ashish





Customer Names started with : ashish
----------------------------------------------------------------------------------------------------
Bill No    Customer Name                  Phone No             Bill Date
----------------------------------------------------------------------------------------------------
2          Ashish                         9727503073           2020-01-04
8          Ashish                         9750184921           2020-01-08
23         Ashish                         9914783969           2020-01-25
----------------------------------------------------------------------------------------------------

Press any key to continue....

In [5]:
# To showcase a old bills and transactions by datetime 
def search_bill():
    clear()
    bill_no = int(input('Enter Bill Number :'))
    sql = f"""select b.bill_id,b.name,b.phone,b.bill_date,t.item_id,t.qty,
          i.item_name,i.price from bills b,transactions t,items i \
       where b.bill_id = t.bill_id AND t.item_id= i.id AND \
       b.bill_id ={bill_no};"""
    cursor.execute(sql) 
    records = cursor.fetchall()
    n = cursor.rowcount

    clear()
    print("Bill No :",bill_no)
    print('-'*100)

    if n<=0:
        print('Bill number {} does not exists'.format(bill_no))
    else:
        print(f'Customer Name : {records[0][1]}  Phone No :{records[0][2]}')
        print(f'Bill Date : {records[0][3]}')
        print('-'*100)
        print('"ID"{:10s} "Item Name"{:30s} "Qty"{:20s} "Price"{:10s} "Amount"{:30s}')
        print('-'*100)

        for row in records:
            print(f'{row[4]:<10d} {row[6]:30s} {row[5]:<20d} {row[7]:.2f} {row[5]*row[7]:>.2f}')
        print('-'*100)
    print('\nPress any key to continue....')
    wait = input()

In [43]:
bill_no = int(input('Enter Bill Number :'))
sql = f"""select b.bill_id,b.name,b.phone,b.bill_date,t.item_id,t.qty,
        i.item_name,i.price from bills b,transactions t,items i \
       where b.bill_id = t.bill_id AND t.item_id= i.id AND \
       b.bill_id ={bill_no};"""
cursor.execute(sql) 
records = cursor.fetchall()
n = cursor.rowcount

clear()
print("Bill No :",bill_no)
print('-'*100)

if n<=0:
    print('Bill number {} does not exists'.format(bill_no))
else:
    print(f'Customer Name : {records[0][1]}  Phone No :{records[0][2]}')
    print(f'Bill Date : {records[0][3]}')
    print('-'*100)
    print('"ID"{:10s} "Item Name"{:30s} "Qty"{:20s} "Price"{:10s} "Amount"{:30s}')
    print('-'*100)
    
    for row in records:
        print(f'{row[4]:<10d} {row[6]:30s} {row[5]:<20d} {row[7]:.2f} {row[5]*row[7]:>.2f}')
    print('-'*100)
print('\nPress any key to continue....')
wait = input()

Enter Bill Number :6





Bill No : 6
----------------------------------------------------------------------------------------------------
Customer Name : Paapu  Phone No :9775467854
Bill Date : 2020-01-06
----------------------------------------------------------------------------------------------------
"ID"{:10s} "Item Name"{:30s} "Qty"{:20s} "Price"{:10s} "Amount"{:30s}
----------------------------------------------------------------------------------------------------
209        Trimmer                        19                   999.00 18981.00
----------------------------------------------------------------------------------------------------

Press any key to continue....

In [51]:
def search_menu():
    while True:
        clear()
        print('      S E A R C H    M E N U ')
        print('-'*100)
        print('1.   Item Name')
        print('2.   Customer information')
        print('3.   Bill information')
        print('4.   Back to main Menu')
        choice = int(input('\n\nEnter your choice (1..4): '))
        if choice==1:
            search_item()
        if choice==2:
            search_customer()
        if choice==3:
            search_bill()
        if choice==4:
            break

In [46]:
while True:
    clear()
    print('      S E A R C H    M E N U ')
    print('-'*100)
    print('1.   Item Name')
    print('2.   Customer information')
    print('3.   Bill information')
    print('4.   Back to main Menu')
    choice = int(input('\n\nEnter your choice (1..4): '))
    if choice==1:
        search_item()
    if choice==2:
        search_customer()
    if choice==3:
        search_bill()
    if choice==4:
        break

      S E A R C H    M E N U
----------------------------------------------------------------------------------------------------
1.   Item Name
2.   Customer information
3.   Bill information
4.   Back to main Menu


Enter your choice (1..4): 2





Enter customer Name :ashish





Customer Names started with : ashish
----------------------------------------------------------------------------------------------------
Bill No    Customer Name                  Phone No             Bill Date
----------------------------------------------------------------------------------------------------
2          Ashish                         9727503073           2020-01-04
8          Ashish                         9750184921           2020-01-08
23         Ashish                         9914783969           2020-01-25
----------------------------------------------------------------------------------------------------

Press any key to continue....






      S E A R C H    M E N U
----------------------------------------------------------------------------------------------------
1.   Item Name
2.   Customer information
3.   Bill information
4.   Back to main Menu


Enter your choice (1..4): 4

In [6]:
# to get information regarding requirement
def report_menu():
    while True:
        clear()
        print('   R E P O R T   M E N U ')
        print('-'*100)
        print('1.   Item List')
        print('2.   Sell Between Dates')
        print('3.   Bill information')
        print('4.   Amount collected')
        print('5.   Back to main Menu')
        choice = int(input('\n\nEnter your choice (1..5): '))
        if choice==1:
            item_list()
        if choice==2:
            date_wise_sell()
        if choice==3:
            bill_information()
        if choice==4:
            amount_collected()
        if choice==5:
            break

In [48]:
while True:
    clear()
    print('   R E P O R T   M E N U ')
    print('-'*100)
    print('1.   Item List')
    print('2.   Sell Between Dates')
    print('3.   Bill information')
    print('4.   Amount collected')
    print('5.   Back to main Menu')
    choice = int(input('\n\nEnter your choice (1..5): '))
    if choice==1:
        item_list()
    if choice==2:
        date_wise_sell()
    if choice==3:
        bill_information()
    if choice==4:
        amount_collected()
    if choice==5:
        break

   R E P O R T   M E N U
----------------------------------------------------------------------------------------------------
1.   Item List
2.   Sell Between Dates
3.   Bill information
4.   Amount collected
5.   Back to main Menu


Enter your choice (1..5): 1





(201, 'Fash wash', 250.75)
(202, 'Perfume', 2500.0)
(203, 'Deodrent', 199.0)
(204, 'Tea Cattel', 240.0)
(205, 'Condoms', 143.0)
(206, 'Hair dryer', 175.0)
(207, 'Suns Cream', 275.0)
(208, 'hair oil', 250.75)
(209, 'Trimmer', 999.0)
(210, 'Eye liner', 1299.0)
(301, 'Feuits & vegetables', 100.0)
(302, 'Meat & Seafood', 1999.0)
(303, 'Coffe', 299.0)
(304, 'Tea powder', 199.0)
(305, 'soups', 99.0)
(306, 'Sauce', 149.0)
(307, 'Cadbary', 179.0)
(308, 'Pasta', 299.0)
(309, 'bread', 299.0)
(310, 'oats', 299.0)
(401, 'Swimsuite', 499.0)
(402, 'Jeans', 999.0)
(403, 'Shirts', 799.0)
(404, 'Skirts', 899.0)
(405, 'Bra', 399.0)
(406, 'Tops', 499.0)
(407, 'gown', 1499.0)
(408, 'Slip', 599.0)
(409, 'babydoll', 499.0)
(410, 'Shorts', 341.0)
(506, 'Milk Product', 75.0)

Press any key to continue.....






   R E P O R T   M E N U
----------------------------------------------------------------------------------------------------
1.   Item List
2.   Sell Between Dates
3.   Bill information
4.   Amount collected
5.   Back to main Menu


Enter your choice (1..5): 5

In [1]:
# to understand overall process added these inputs
def main_menu():
    while True:
        clear()
        print('      M A I N   M E N U')
        print('-'*100)
        print('1.   Add New Item')
        print('2.   Modify Existing Item')
        print('3.   Billing')
        print('4.   Search Menu')
        print('5.   Report Menu')
        print('6.   Exit')
        choice = int(input('\n\nEnter your choice (1..6): '))
        if choice==1:
            add_item()
        if choice==2:
            modify_item()
        if choice==3:
            billing()
        if choice==4:
            search_menu()
        if choice==5:
            report_menu()
        if choice==6:
            break

In [60]:
while True:
    clear()
    print('      M A I N   M E N U')
    print('-'*100)
    print('1.   Add New Item')
    print('2.   Modify Existing Item')
    print('3.   Billing')
    print('4.   Search Menu')
    print('5.   Report Menu')
    print('6.   Exit')
    choice = int(input('\n\nEnter your choice (1..6): '))
    if choice==1:
        add_item()
    if choice==2:
        modify_item()
    if choice==3:
        billing()
    if choice==4:
        search_menu()
    if choice==5:
        report_menu()
    if choice==6:
        break

      M A I N   M E N U
----------------------------------------------------------------------------------------------------
1.   Add New Item
2.   Modify Existing Item
3.   Billing
4.   Search Menu
5.   Report Menu
6.   Exit


Enter your choice (1..6): 1





Add New Item - Screen
----------------------------------------------------------------------------------------------------
Enter new Item Name : kitbag
Enter Item Price : 4000
Enter The Item Id: 510


New Item added successfully.....
Press any key to continue....






      M A I N   M E N U
----------------------------------------------------------------------------------------------------
1.   Add New Item
2.   Modify Existing Item
3.   Billing
4.   Search Menu
5.   Report Menu
6.   Exit


Enter your choice (1..6): 3
Enter customer Name :shubham
Name of Customer:  shubham
Enter Phone No :1544941549
Phone No of Customer:  1544941549
Enter the Date Purchase (format='YYYY-MM-DD') : 2020-01-03
The Date of Purchase is:  2020-01-03
Enter item No (0 to stop) :302
Enter Item Qty :10
Enter item No (0 to stop) :304
Enter Item Qty :50
Enter item No (0 to stop) :501
Item Not found
Enter item No (0 to stop) :509
Enter Item Qty :10
Enter item No (0 to stop) :0
[509, 'Footboll', 3000.0, 10]
[[302, 'Meat & Seafood', 1999.0, 10], [304, 'Tea powder', 199.0, 50], [509, 'Footboll', 3000.0, 10]]





                     Absolute Solution
                     D- Block Chander Nagar, GZB
                     Phone: 9871816901, Email: rakesh@binarynote.com
Bill No :27        Date :2020-01-03
----------------------------------------------------------------------------------------------------
Customer Name :shubham          Phone No :1544941549
----------------------------------------------------------------------------------------------------
Item Id     Item Name                Price            Qty         Amount
----------------------------------------------------------------------------------------------------
Item Id		 Item Name		 Price		 Qty		 Amount
302		 Meat & Seafood		 1999.0		 10		 19990.0
Item Id		 Item Name		 Price		 Qty		 Amount
304		 Tea powder		 199.0		 50		 9950.0
Item Id		 Item Name		 Price		 Qty		 Amount
509		 Footboll		 3000.0		 10		 30000.0
----------------------------------------------------------------------------------------------------
Total Payable Amount : 59940.0

Press any key to continue........






      M A I N   M E N U
----------------------------------------------------------------------------------------------------
1.   Add New Item
2.   Modify Existing Item
3.   Billing
4.   Search Menu
5.   Report Menu
6.   Exit


Enter your choice (1..6): 6

In the end I would like to thank all of my colleagues, my teachers who helped me, and my team at every part of our journey, and in making these projects a success. Last but not the least I would like to thank my team, my friends for helping me through the project.